dependencies:
  - matplotlib
  - numpy
  - pandas
  -  absl-py
  -  alembic
  -  arcgis
  -  asn1crypto
  -  astor
  -  async-generator
  -  audioread
  -  backcall
  -  beautifulsoup4
  -  bleach
  -  boto
  -  boto3
  -  botocore
  -  Bottleneck
  -  bz2file
  -  certifi
  -  cffi
  -  chardet
  -  Click
  -  cloudpickle
  -  conda
  -  cryptography
  -  cycler
  -  cymem
  -  cytoolz
  -  dask
  -  dataclasses
  -  decorator
  -  defusedxml
  -  dill
  -  dlib
  -  docutils
  -  entrypoints
  -  et-xmlfile
  -  face-recognition
  -  face-recognition-models
  -  fastai
  -  fastprogress
  -  future
  -  gast
  -  gensim
  -  gofer-grader
  -  grpcio
  -  h5py
  -  html5lib
  -  idna
  -  ipykernel
  -  ipyleaflet
  -  ipyparallel
  -  ipython
  -  ipython-genutils
  -  ipywidgets
  -  jdcal
  -  jedi
  -  jeepney
  -  jieba
  -  Jinja2
  -  jmespath
  -  joblib
  -  jsonschema
  -  jupyter
  -  jupyter-client
  -  jupyter-console
  -  jupyter-core
  -  jupyterlab
  -  jupyterlab-server
  -  Keras
  -  Keras-Applications
  -  Keras-Preprocessing
  -  keyring
  -  kiwisolver
  -  librosa
  -  llvmlite
  -  lxml
  -  Mako
  -  Markdown
  -  MarkupSafe
  -  matplotlib
  -  metakernel
  -  mistune
  -  msgpack
  -  msgpack-numpy
  -  msgpack-python
  -  murmurhash
  -  nbconvert
  -  nbformat
  -  nbgitpuller
  -  nbgrader
  -  nbresuse
  -  networkx
  -  notebook
  -  nteract-on-jupyter
  -  numba
  -  numexpr
  -  numpy
  -  openpyxl
  -  Orange3-Associate
  -  pamela
  -  pandas
  -  pandocfilters
  -  parso
  -  patsy
  -  pexpect
  -  pickleshare
  -  Pillow
  -  pip
  -  plac
  -  preshed
  -  prometheus-client
  -  prompt-toolkit
  -  protobuf
  -  psutil
  -  ptyprocess
  -  pycosat
  -  pycparser
  -  Pygments
  -  pyOpenSSL
  -  pyparsing
  -  pyshp
  -  PySocks
  -  python-dateutil
  -  python-editor
  -  python-oauth2
  -  python-snappy
  -  pytz
  -  PyWavelets
  -  PyYAML
  -  pyzmq
  -  qtconsole
  -  regex
  -  requests
  -  resampy
  -  ruamel-yaml
  -  s3transfer
  -  scikit-image
  -  scikit-learn
  -  scipy
  -  seaborn
  -  SecretStorage
  -  Send2Trash
  -  setuptools
  -  simplejson
  -  six
  -  sklearn
  -  smart-open
  -  spacy
  -  SQLAlchemy
  -  statsmodels
  -  tensorboard
  -  tensorflow
  -  termcolor
  -  terminado
  -  testpath
  -  Theano
  -  thinc
  -  toolz
  -  torch
  -  torchvision-nightly
  -  tornado
  -  tqdm
  -  traitlets
  -  traittypes
  -  tushare
  -  typing
  -  ujson
  -  urllib3
  -  wcwidth
  -  webencodings
  -  Werkzeug
  -  wheel
  -  wordcloud
  -  wrapt
  -  wurlitzer
  -  xarray
  -  xlrd
